name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Збірка
      run: mvn clean install
    - name: Розгортання
      run: echo "Розгортання завершено."
